version: "3.7"

services:
  cookie_access:
    hostname: cookies
    build:
      context: cookie_access
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=cookies.admin.sixctf.event
    environment:
      FLAG: flag{this_is_cookie_flag}
      ADMIN_PASSWORD: admin_password
    depends_on:
      - creds

  main:
    hostname: main
    build:
      context: main
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=admin.sixctf.event
    environment:
      COOKIES_DOMAIN: cookies.admin.sixctf.event
      AUTH_DOMAIN: auth.admin.sixctf.event
      CALCULATOR_DOMAIN: calculator.admin.sixctf.event
      BASE_DOMAIN: admin.sixctf.event

  creds:
    hostname: creds
    build:
      context: creds
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=auth.admin.sixctf.event
    environment:
      FLAG: flag{this_is_a_flag}
      JWT_SECRET: the_jwt_secret_from_env
      ADMIN_HASH_PASSWORD: admin_password

  calculator:
    hostname: calculator
    build:
      context: calculator
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=calculator.admin.sixctf.event
    environment:
      FLAG: flag{this_is_a_flag}