version: "3.7"

services:
  cookie_access:
    hostname: cookies
    build:
      context: cookie_access
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=cookies.admin.sixctf.event
    environment:
      FLAG: IUT{B3_Pr0Ud_0F_2eRv3r_C0nF1g}
      ADMIN_PASSWORD: admin_password
    depends_on:
      - creds

  main:
    hostname: main
    build:
      context: main
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=admin.sixctf.event
    environment:
      COOKIES_DOMAIN: cookies.admin.sixctf.event
      AUTH_DOMAIN: auth.admin.sixctf.event
      CALCULATOR_DOMAIN: calculator.admin.sixctf.event
      BASE_DOMAIN: admin.sixctf.event

  creds:
    hostname: creds
    build:
      context: creds
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=auth.admin.sixctf.event
    environment:
      FLAG: IUT{P4TH_Tr4v3rs4l_1s_4w3s0M3}
      JWT_SECRET: the_jwt_secret_from_env
      ADMIN_HASH_PASSWORD: admin_password

  calculator:
    hostname: calculator
    build:
      context: calculator
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=calculator.admin.sixctf.event
    environment:
      FLAG: IUT{3vAl_Is_4v1l_b3_c4r3fUl}