version: "3.7"

services:
  cookie_access:
    hostname: cookies
    build:
      context: cookie_access
      dockerfile: Dockerfile
    user: www-data
    environment:
      FLAG: IUT{B3_Pr0Ud_0F_2eRv3r_C0nF1g}
      ADMIN_PASSWORD: admin_password

  main:
    hostname: main
    build:
      context: main
      dockerfile: Dockerfile

  creds:
    hostname: creds
    build:
      context: creds
      dockerfile: Dockerfile
    environment:
      FLAG: IUT{P4TH_Tr4v3rs4l_1s_4w3s0M3}
      JWT_SECRET2: the_jwt_secret_from_env
      ADMIN_HASH_PASSWORD: admin_password

  calculator:
    hostname: calculator
    build:
      context: calculator
      dockerfile: Dockerfile
    environment:
      FLAG: IUT{3vAl_Is_4v1l_b3_c4r3fUl}

  nginx:
    hostname: nginx
    build: 
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "50000:80"