version: '3.3'

services:
  agarsc:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "30000:8080"
    container_name: agarsc

  agarcc:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    container_name: agarcc
