version: '3.7'

services:
  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000
    ports:
      - 80:8000

  mysql:
    image: mysql:8.0
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test