doctrine:
    dbal:
        connections:
            sqlite:
                url: '%env(resolve:SQLITE_DATABASE_URL)%'
                driver: 'pdo_sqlite'
                server_version: '3.27.2'
                profiling_collect_backtrace: '%kernel.debug%'
            mysql:
                url: '%env(resolve:MYSQL_DATABASE_URL)%'
                server_version: '8.2.0'
                profiling_collect_backtrace: '%kernel.debug%'

        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
    orm:
        auto_generate_proxy_classes: false
        enable_lazy_ghost_objects: false
        entity_managers:
            mysql:
                connection: mysql
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                report_fields_where_declared: true
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                repository_factory: App\Repository\orm\RepositoryFactory
            sqlite:
                connection: sqlite
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/'
                        prefix: 'App\Entity'
                        alias: App
                report_fields_where_declared: true
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                repository_factory: App\Repository\orm\RepositoryFactory

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
