gos_web_socket:
    server:
        # The host IP address on the server which connections for the websocket server are accepted.
        host: 0.0.0.0

        # The port on the server which connections for the websocket server are accepted.
        port: 8080

        router:
            resources:
                -
                    resource: '%kernel.project_dir%/config/pubsub/websocket/*'
                    type: 'glob'
    
    authentication:
        enable_authenticator: true
        providers:
            app:
        storage:
            type: in_memory
