# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your sAuthManager::classervices.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    App\Websocket\Rpc\:
        resource: '../src/Websocket/Rpc'
        tags: ['gos_web_socket.rpc']
    
    
    App\Websocket\Topic\:
        resource: '../src/Websocket/Topic'
        tags: [ 'gos_web_socket.topic' ]

    # App\Repository\contracts\DatabasePool:
    #     arguments: [
    #         '%doctrine_mongodb.odm.default_document_manager%',
    #         '%doctrine.orm.mysql_entity_manager%',
    #         '%doctrine.orm.sqlite_entity_manager%'
    #     ]
    
    App\Neo4j\bridge\EntityManagerFactory:    
    
    GraphAware\Neo4j\OGM\EntityManagerInterface:
        factory: [
            '@App\Neo4j\bridge\EntityManagerFactory',
            'create'
        ]
        

    App\Command\:
        resource: '../src/Command'
        tags: ['console.command']
