stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image:
      name: ubuntu:latest
      entrypoint: [""]

  before_script:
      - apt update -qy && apt install python3 python3-pip openssh-client curl gnupg lsb-core software-properties-common -qy
      - eval $(ssh-agent -s)
      - echo "${SSH_Key}" | ssh-add -
      - mkdir -p ~/.ssh
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
      - pip install ctfcli

  script:
    - ssh interiut@192.168.1.210 "rm -rf /home/interiut/R_Place_1"
    # - ctf challenge add . && ctf challenge install $PWD
    - ctf challenge add . && ctf challenge sync $PWD
    - ssh interiut@192.168.1.210 "mkdir -p /home/interiut/R_Place_1/"

    - scp -r ./public interiut@192.168.1.210:/home/interiut/R_Place_1/public/
    - scp -r ./src interiut@192.168.1.210:/home/interiut/R_Place_1/src/
    - scp ./base.png interiut@192.168.1.210:/home/interiut/R_Place_1/base.png
    - scp ./Cargo.toml interiut@192.168.1.210:/home/interiut/R_Place_1/Cargo.toml
    - scp ./Cargo.lock interiut@192.168.1.210:/home/interiut/R_Place_1/Cargo.lock
    - scp ./docker-compose.yml interiut@192.168.1.210:/home/interiut/R_Place_1/docker-compose.yml
    - scp ./Dockerfile interiut@192.168.1.210:/home/interiut/R_Place_1/Dockerfile

    - ssh interiut@192.168.1.210 "cd /home/interiut/R_Place_1/ && sudo docker-compose up -d --build"
    - echo "Container Start !"


